FROM amazonlinux:2023

RUN dnf install -y aws-nitro-enclaves-cli jq util-linux \
    && dnf clean all \
    && rm -rf /var/cache/dnf

COPY enclave.eif /enclave.eif
COPY deploy/pod_entrypoint.sh /pod_entrypoint.sh

RUN chmod 0755 /pod_entrypoint.sh

ENTRYPOINT ["/pod_entrypoint.sh"]