apiVersion: v1
kind: Secret
metadata:
  name: {{ include "zero-copy-pii-proxy.fullname" . }}-secrets
  labels:
    {{- include "zero-copy-pii-proxy.labels" . | nindent 4 }}
type: Opaque
stringData:
  PROXY_API_KEY: {{ .Values.secrets.apiKey | quote }}
