apiVersion: v1
kind: Secret
metadata:
  name: {{ include "zero-copy-pii-proxy.fullname" . }}-secrets
  labels:
    {{- include "zero-copy-pii-proxy.labels" . | nindent 4 }}
type: Opaque
stringData:
  AUTH_TOKENS: {{ required "At least one auth token is required!" .Values.secrets.authTokens | quote }}
  PROXY_PRIVATE_KEY: {{ required "A valid proxyPrivateKey is required!" .Values.secrets.proxyPrivateKey | quote }}
