apiVersion: v1
kind: Secret
metadata:
  name: {{ include "zero-copy-pii-proxy.fullname" . }}-secrets
  labels:
    {{- include "zero-copy-pii-proxy.labels" . | nindent 4 }}
type: Opaque
stringData:
  {{- if not .Values.secrets.authTokens }}
  PROXY_API_KEY: {{ .Values.secrets.apiKey | quote }}
  {{- end }}
  {{- if .Values.secrets.authTokens }}
  AUTH_TOKENS: {{ .Values.secrets.authTokens | quote }}
  {{- end }}
  PROXY_PRIVATE_KEY: {{ required "A valid proxyPrivateKey is required!" .Values.secrets.proxyPrivateKey | quote }}
